# Generated by Django 6.0.1 on 2026-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('admin', 'Admin'), ('doctor', 'Doctor')], default='patient', max_length=20),
        ),
    ]
